### ISSUE TITLE
Can't change button icon once set

### ISSUE THREAD

**Issue by vierkantemeter** [modmore/QuickstartButtons#15]
I have to resubmit closed issue #13 . I have about 4 installs which all have the problem when an icon is set, it cannot be changed anymore. Also in the quickstartbuttons_buttons table nothing changed.

No errors in the MODX or Apache log. I can't really figure out why this happens.

MODX 2.2.15 (4x)
QuickstartButtons 1.1.1
Firefox 31

If you need more info, or want to have a peek at my installs let me know, because I :heart: Quickstartbuttons, and want to make it even better.

**Comment by Mark-H** [comment]
Well, it's definitely after the MODX Weekend. :P 

I've not yet witnessed this myself yet. What icon are you selecting, one of the FA ones or a custom one?
