### ISSUE TITLE
System actions not displaying full list in 2.3.2

### ISSUE THREAD

**Issue by eighthday** [modmore/QuickstartButtons#18]
No options for create resource etc:

![quick](https://cloud.githubusercontent.com/assets/4104767/5157408/23461490-7302-11e4-901c-9643688fd315.gif)

**Comment by Lefthandmedia** [comment]
Is there a fix for this?

**Comment by Mark-H** [comment]
Not yet, this requires architectural changes to QuickstartButtons.

**Comment by Mark-H** [comment]
There is however a workaround, which is instead of selecting the action, simply adding `?a=resource/update&id=33` to the Full Link option.

**Comment by Mark-H** [comment]
I've just released an update (`1.2.0-rc1`) that loads core actions into the dropdown again. For 2.2-style actions they will continue to show up and work like they did, however for 2.3-style non-core actions there does not seem to be a way to load them through the MODX APIs. For those you'll need to specify a link of `?a=action&namespace=thepackage` instead.
