### ISSUE TITLE
The problem with displaying icons in 2.3

### ISSUE THREAD

**Issue by SoftAlex** [modmore/QuickstartButtons#20]
Icons are displayed only if it is turned off system var "compress_css"

**Comment by vierkantemeter** [comment]
I've got this problem too with MODX 2.4.0-pl and QSB 1.2.0.

Strange thing is, this only happens with my admin account. When I login as a content editor, with compress_css ON, the icons are shown. Maybe this is related to issue https://github.com/modmore/QuickstartButtons/issues/16 ?

**Comment by Mark-H** [comment]
This is fixed in MODX 2.5 (because the compress_css setting has a different meaning there), and should also be resolved in 1.3 as it's loading the font awesome css differently as of that release.

**Comment by Mark-H** [comment]
Though it's a bit hard for me to test this as I can't run it with compress_css enabled on my dev environment anyway, so if you continue to see issues with this in 1.3 on 2.4, please let me know.
