### ISSUE TITLE
Upgrade FontAwesome to latest version (4.3)

### ISSUE THREAD

**Issue by vierkantemeter** [modmore/QuickstartButtons#21]
There are some cool icons added in the newer versions of FontAwesome. Please upgrade it to the latest version. (Using 4.0.3, most recent 4.3.0).

Tried to upgrade manually, but with no luck. Any instructions to do a manual upgrade?

**Comment by Mark-H** [comment]
Updating the files (in particular the icons.css) and then re-running the install should do the trick, but we'll get the included version up to speed.

**Comment by jpdevries** [comment]
I submitted a PR which adds the latest version of FontAwesome to a new Grunt workflow
https://github.com/modmore/QuickstartButtons/commit/113bca3e1fc84a412ba138f58398c5802e8a42dd

It works much like the Revolution Grunt Workflow does however in Revo fetch the font awesome sass files and then include those with the `main.css` file so it is all in one. I intentionally left the fontawesome css separate from the QuickstartButtons CSS to go along with what is proposed in #26

**Comment by inreti** [comment]
FA 4.4 is current release now.

**Comment by jcdm** [comment]
+1 for this - I don't have a Grunt workflow (that I know of ;) )

**Comment by Mark-H** [comment]
Updated to 4.5 in 1.3!
