### ISSUE TITLE
Javascript handler field cuts off long(er) scripts

### ISSUE THREAD

**Issue by hugopeek** [modmore/QuickstartButtons#22]
Wanted to add some JS for clearing custom cache partitions to a button, but that seems to be too long for the Javascript Handler field under Button > Update > Link..

Can this be a textarea maybe, that accepts more characters / lines? Same as when you edit a Top Menu item?

I tried changing the xtype of the handler field to textarea, and adding a maxLength : 5000 setting under assets/components/quickstartbuttons/js/mgr/widgets/buttons.windows.js, but that didn't work.. It's being cut short someplace else, but I don't know where to look now :)

**Comment by Mark-H** [comment]
The handler field is limited to 255 characters: https://github.com/modmore/QuickstartButtons/blob/master/core/components/quickstartbuttons/model/schema/quickstartbuttons.mysql.schema.xml#L40

Maybe you can load in the function with a plugin, and just call the function inside the handler?
