### ISSUE TITLE
Resource Tree problems with template icons

### ISSUE THREAD

**Issue by inreti** [modmore/QuickstartButtons#29]
We use template icons a lot in our installations. All of them (v2.3.5) show problems at the dashboard displaying the resource tree: some of the icons there are not shown, instead cryptics signs (unicode char?) show up. The problem definitely occurs in FF (chrome works). Icons of the resource tree are shown correctly on any other page - but not on the dashboard if QuickStartButtons widget is there. 
Here is a screenshot of the RT in Firefox showing the problem:

![qs_buttons_error1](https://cloud.githubusercontent.com/assets/2852461/8961726/2105a488-3617-11e5-8151-4f6442133642.png)

And this is how it is expected to look like:

![screenshot from 2015-07-29 17 26 08](https://cloud.githubusercontent.com/assets/2852461/8961732/2bb9fec4-3617-11e5-96a6-c8484e45079e.png)

The icons not working here are _-building_ and _-newspaper-o_ - both of them not available at QuickstartButtons. So I assume the cause is the old Fontawesome version of QB, which seems to overwrite the dashboards css somehow causing the resource tree icons having the "wrong" font.

If this cannot be fixed in general, it might be the best to remove the FA as supposed in #26 to prevent any such errors now and in the future (hard to keep the core and QB versions of Font-Awesome in sync, and quite useless to deliver redundancy).

**Comment by inreti** [comment]
Just realized I already opened an issue for that some weeks ago (#25) :-(. I should read my own comments...
Anyway, closed that one in favour of this which provides a bit more information.

**Comment by Mark-H** [comment]
This appears fixed when using 1.3. Likely related to #35 one way or another? Please reopen if you can still replicate the issue with 1.3. 

Be sure to specify the icon as `icon-building`, and not just `building`, though I guess that's just a typo in your issue.
