### ISSUE TITLE
Systems Action not loading after save

### ISSUE THREAD

**Issue by jcdm** [modmore/QuickstartButtons#31]
The image shows the CMP for a button where I had selected 'core - resource/update' from the Systems Action drop list. As you can see this hasn't repopulated and I find that if I save again at this point, the action_key field is erased in the DB record, leaving it actionless.

MODX 2.4 on MODX Cloud

![screen shot 2015-09-17 at 12 31 13 am](https://cloud.githubusercontent.com/assets/2160585/9908576/7311828c-5cd3-11e5-93f3-a29d72dee12d.png)

**Comment by sonicpunk** [comment]
I have this exact problem as well.  After adding a new button, the systems action from already saved buttons get deleted.

**Comment by janwidmer** [comment]
Same Problem here.

**Comment by Mark-H** [comment]
This has been fixed in 1.3. Thanks for the reports!
