### ISSUE TITLE
Unable to configure 2.3-style actions and namespaces

### ISSUE THREAD

**Issue by jcdm** [modmore/QuickstartButtons#32]
The MIGX CMP requires the action in the URL to be 'index' rather than an ID. When I select 'migx - index' from the Systems Action list, what's saved to the database is an integer in the action_id field. When I try to load this link it's a white screen of death.

If I go into the database and directly modify the fields as per the below, everything works as expected: 
![screen shot 2015-09-17 at 12 36 13 am](https://cloud.githubusercontent.com/assets/2160585/9908740/247f40ea-5cd4-11e5-9ea9-31ef798cccf3.png)

But, there doesn't seem to be a way to configure these fields via the CMP. Certainly if I modify them in the DB and then load the CMP, the values don't show up anywhere.

Could we please have a way to configure those fields?

MODX 2.4 on MODX Cloud

**Comment by sonicpunk** [comment]
I am having the same issue!  Thanks for describing it so well!

**Comment by Mark-H** [comment]
This is not a MIGX specific issue, rather it's an issue that has to do with the way you can enter 2.3+ style actions.

I've developed a fix (included in 1.3) that allows you to type in the action, and choose the namespace manually. That should do the trick, though I'm not very happy with the complexity in the linking dialog currently. Perhaps it's time to start speccing out a v2 :D
