### ISSUE TITLE
Linking to Media/Browser is missing

### ISSUE THREAD

**Issue by sebastian-marinescu** [modmore/QuickstartButtons#34]
Hi, first of all: Great package!

I'm currently using it the first time and began with adding buttons. 
I expected that I could add a link to the action "media/browser".

My current workaround is to use the full-link-field and set it to:
?a=media/browser

Although this is not critical, I think it would be great for future versions.

What do you think?

**Comment by Mark-H** [comment]
Fixed in 1.3!

**Comment by sebastian-marinescu** [comment]
Thanks! :+1:
