### ISSUE TITLE
Displaying dashboard with QuickstartButtons kills manager in MODX 2.5.0-rc1

### ISSUE THREAD

**Issue by digitalpenguin** [modmore/QuickstartButtons#37]
If I add the QuickStartButtons widget to my dashboard, the manager displays a blank page when attempting to view the dashboard. Thus, logging in to the manager will display nothing.

They way to fix this is by manually removing the QuickstartButtons row from the database table:
modx_dashboard_widget_placement

Loading the dashboard then works fine again.
Adding other widgets to the dashboard appears to work without problems.

Can anyone else replicate this?

**Comment by Mark-H** [comment]
This is a bug in 2.5.0-rc1, which has already been fixed in git for the next release.

**Comment by digitalpenguin** [comment]
Great thanks!
