### ISSUE TITLE
Unambiguous English texts

### ISSUE THREAD

**Issue by enigmatic-user** [modmore/QuickstartButtons#47]
Several years ago I discussed the usage of "delete" vs "remove" and "edit" vs "update" with someone from the MODX team. In my eyes it would be clearer - especially for translators - to use "delete" when an item is destroyed completely, and "remove" when it still exists but isn't attached anymore after the action. Also I think that "edit" should be used when the user can make changes to an item, while "update" means something like reloading or possibly applying a newer version of something.

In MODX, several phrases were changed back then, even if it's still not consistent. It's easier to differentiate that way, otherwise the translator always has to consult the UI to see what is meant, and also a user might not be sure which effect the action might have.

**Comment by sebastian-marinescu** [comment]
So... what you are saying is, that "Update Button" / "Remove Button" in the context-menu, and also "Update Set" / "Remove Set" should from an UX point of view be changed respectively to "Edit" and "Delete"?

**Comment by enigmatic-user** [comment]
Yes, I think it would be a good idea to change these phrases to "Edit Button" / "Delete Button" and "Edit Set" / "Delete Set" respectively.

**Comment by sebastian-marinescu** [comment]
I'm on your side on this one, as clear communication is king. 
If @Mark-H also sees it this way, I can prepare a PR for that.

**Comment by Mark-H** [comment]
Works for me!

I'd love to see a more generic document describing this sort of thing for core and other extras too. Would be good for the usability if everything is consistent.
